services: 
  db_students: 
    image: postgres
    container_name: db_students
    restart: always
    ports: 
      - 8000:5432
    env_file:
      - .env
    volumes:
      - pg_students:/var/lib/postgresql/data

  node_students:
    container_name: node_students
    build: . 
    ports: 
      - 5000:5000
    depends_on:
      - db_students
    env_file:
      - .env

volumes:
  pg_students: